2020-04-16 19:23:42,222 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:23:42,895 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:24:00,505 ERROR: Exception on /login [GET] [in /home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ghost/myrepos/Flog/app/routes.py", line 28, in login
    form = LoginForm()
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-04-16 19:26:21,961 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:26:22,592 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:26:26,172 ERROR: Exception on /login [GET] [in /home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ghost/myrepos/Flog/app/routes.py", line 28, in login
    form = LoginForm()
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 141, in generate_csrf_token
    token_key=self.meta.csrf_field_name
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 35, in generate_csrf
    message='A secret key is required to use CSRF.'
  File "/home/ghost/mydocs/flask/falskenv/lib/python3.7/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
2020-04-16 19:34:24,945 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:34:25,603 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:37:25,413 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
2020-04-16 19:37:28,125 INFO: Microblog startup [in /home/ghost/myrepos/Flog/app/__init__.py:69]
